spring:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_HOST:postgres}:5432/${MAIN_DB_NAME:tenminread_main_db}   # ← 변경
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:1234}

    bookdb:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_HOST:postgres}:5432/${BOOK_DB_NAME:tenminread_book_db}   # ← 변경
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:1234}

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
