spring:
  datasource:

    # (1) 메인 DB (User, Book, Quiz 등)
    main:
      jdbc-url: jdbc:postgresql://localhost:5432/tenminread_main_db
      username: postgres
      password: "0820"
      driver-class-name: org.postgresql.Driver

    # (2) 서브 DB (BookText, SummaryText 등)
    bookdb:
      jdbc-url: jdbc:postgresql://localhost:5432/tenminread_book_db
      username: postgres
      password: "0820"
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
