spring:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${DB_HOST:postgres}:5432/${MAIN_DB_NAME:tenminread_main_db}
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:1234}

    bookdb:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${DB_HOST:postgres}:5432/${BOOK_DB_NAME:tenminread_book_db}
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:1234}

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none        # ✅ 운영은 Flyway로만 스키마 관리
    properties:
      hibernate:
        format_sql: false
